version: "3.7"
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
      - "./docker/nginx/log:/var/log/nginx"
      - ".:/usr/share/nginx/html"
    networks:
      - app_network
    container_name: "iwan-nginx"
  php-fpm:
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./docker/php/php-fpm.d:/usr/local/etc/php-fpm.d"
      - "./docker/php/log:/usr/local/var/log"
      - ".:/usr/share/nginx/html"
    networks:
      - app_network
    container_name: "iwan-php-fpm"
  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/my.cnf:/usr/local/mysql/my.cnf"
      - "./docker/mysql/data:/var/lib/mysql"
    networks:
      - app_network
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: "iwan-mysql"
networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16