#!/usr/bin/env php
<?php
use Sys\Application;
use Sys\Config;

defined('ROOT') || define('ROOT', realpath(__DIR__));

require ROOT . '/vendor/autoload.php';

try {
    $application = new Application();
    $application->console(new Config(ROOT . '/config.php'));
} catch (Throwable $e) {
}

//use Symfony\Component\Console\Application;
//
//use Phinx\Console\PhinxApplication;
//
//$application = new PhinxApplication();

//$application = new Application();

// ... register commands

//$application->run();
